<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Settings</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <style>
        body {
            font-family: 'Segoe UI', Arial, sans-serif;
            margin: 0;
            background: #f3f2f1;
            color: #323130;
        }
        .page {
            max-width: 900px;
            margin: 24px auto;
            padding: 0 16px;
        }
        .card {
            background: #fff;
            border: 1px solid #edebe9;
            border-radius: 2px;
            padding: 16px;
        }
        .toolbar {
            display: flex;
            gap: 8px;
            align-items: center;
            margin-bottom: 10px;
        }
        .btn {
            border: 1px solid #8a8886;
            background: #fff;
            color: #323130;
            border-radius: 2px;
            padding: 8px 12px;
            font-size: 12px;
            font-weight: 600;
            cursor: pointer;
        }
        .btn-primary {
            border-color: #106ebe;
            background: #106ebe;
            color: #fff;
        }
        .token {
            width: 100%;
            border: 1px solid #8a8886;
            border-radius: 2px;
            padding: 8px;
            font-family: Consolas, "Courier New", monospace;
            background: #f3f2f1;
            margin-bottom: 8px;
        }
        .help {
            margin: 4px 0;
            font-size: 12px;
            color: #605e5c;
        }
        .back {
            margin-top: 10px;
            display: inline-block;
            text-decoration: none;
            color: #106ebe;
        }
    </style>
</head>
<body>
<div class="page">
    <div class="card">
        <h2 style="margin-top:0;">Settings</h2>
        <h3 style="margin:0 0 10px; font-size:16px;">D365 Token</h3>
        <div class="toolbar">
            <button id="generate-btn" class="btn btn-primary" type="button">Generate token</button>
            <button id="copy-btn" class="btn" type="button">Copy token</button>
        </div>
        <input id="token-output" class="token" type="text" value="{{ $token?->access_token ?? '' }}" readonly>
        <p id="status" class="help">
            @if($token)
                Last generated at {{ $token->created_at?->format('d M Y H:i:s') }}. Expires at {{ $token->expires_at?->format('d M Y H:i:s') }}.
            @else
                No token generated yet.
            @endif
        </p>
        <p id="remaining" class="help">
            @if($token)
                Seconds remaining: {{ $token->secondsRemaining() }}.
            @endif
        </p>
        <a class="back" href="{{ route('dashboard') }}">Back to Dashboard</a>
    </div>
</div>

<script>
    const csrfToken = document.querySelector('meta[name="csrf-token"]')?.content ?? '';
    const generateBtn = document.getElementById('generate-btn');
    const copyBtn = document.getElementById('copy-btn');
    const tokenOutput = document.getElementById('token-output');
    const statusEl = document.getElementById('status');
    const remainingEl = document.getElementById('remaining');
    let intervalId = null;

    const clearTicker = () => {
        if (intervalId) {
            clearInterval(intervalId);
            intervalId = null;
        }
    };

    const startTicker = (seconds) => {
        clearTicker();
        let remaining = Number(seconds) || 0;
        const tick = () => {
            if (remaining <= 0) {
                clearTicker();
                remainingEl.textContent = 'Token expired.';
                return;
            }
            remainingEl.textContent = `Seconds remaining: ${remaining}.`;
            remaining -= 1;
        };
        tick();
        intervalId = setInterval(tick, 1000);
    };

    generateBtn.addEventListener('click', async () => {
        statusEl.textContent = 'Generating token...';
        remainingEl.textContent = '';
        clearTicker();
        try {
            const response = await fetch("{{ route('settings.token.generate') }}", {
                method: 'POST',
                headers: {
                    'X-CSRF-TOKEN': csrfToken,
                    Accept: 'application/json',
                },
            });
            const payload = await response.json().catch(() => ({}));
            if (!response.ok || payload?.status !== true) {
                throw new Error(payload?.message || 'Token generation failed.');
            }

            tokenOutput.value = payload.full_token || '';
            statusEl.textContent = `Generated by ${payload.generated_by ?? '-'} at ${payload.generated_at_human ?? '-'}. Expires at ${payload.expires_at_human ?? '-'}.`;
            startTicker(payload.seconds_remaining || 0);
        } catch (error) {
            statusEl.textContent = error.message;
        }
    });

    copyBtn.addEventListener('click', async () => {
        if (!tokenOutput.value.trim()) {
            statusEl.textContent = 'No token to copy.';
            return;
        }
        try {
            await navigator.clipboard.writeText(tokenOutput.value.trim());
            statusEl.textContent = 'Token copied.';
        } catch (error) {
            statusEl.textContent = 'Copy failed.';
        }
    });

    @if($token)
    startTicker({{ $token->secondsRemaining() }});
    @endif
</script>
</body>
</html>
